#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  devNamespace: tap-dev
  domains:
    learningCenter: learningcenter.tap.tanzu4u.net
    knative: apps.tap.tanzu4u.net
    metadataStore: metadata-store.tap.tanzu4u.net:443
    appliveview:
          host: appliveview.tap.tanzu4u.net
          port: 443

domain: tap.tanzu4u.net
tls:
  secretName: tls
  namespace: tanzu-system-ingress