#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tanzu4u.net
  namespace: tanzu-system-ingress
  annotations:
    kapp.k14s.io/change-group: "tls-cert-request"
    kapp.k14s.io/change-rule.cert-manager: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.tanzu-app-platform: "upsert after upserting tanzu-app-platform"
    kapp.k14s.io/change-rule.tanzu-app-platform-configs: "upsert after upserting tanzu-app-platform-configs"
    kapp.k14s.io/change-rule.3: "delete after deleting tanzu-app-platform"
spec:
  commonName: tap-gui.tap.tanzu4u.net
  isCA: true
  secretName: tls
  privateKey:
      rotationPolicy: Always
  dnsNames:
    - '*.apps.tap.tanzu4u.net'
    - 'tap-gui.tap.tanzu4u.net'
    - 'metadata-store.tap.tanzu4u.net'
    - 'api-portal.tap.tanzu4u.net'
    - '*.learningcenter.tap.tanzu4u.net'
    - 'api.tap.tanzu4u.net'
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-production
    kind: ClusterIssuer

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tls
  namespace: tanzu-system-ingress
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting tanzu-app-platform"
    kapp.k14s.io/change-rule.1: "upsert after upserting tanzu-app-platform-configs"
    kapp.k14s.io/change-rule.2: "delete after deleting tanzu-app-platform"
spec:
  toNamespaces:
  - '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tls
  namespace: learningcenter
  annotations:
    kapp.k14s.io/change-group: "import-tls-secret-to-learningcenter"
    kapp.k14s.io/change-rule.0: "upsert after upserting tanzu-app-platform"
    kapp.k14s.io/change-rule.1: "upsert after upserting tanzu-app-platform-configs"
    kapp.k14s.io/change-rule.2: "delete after deleting tanzu-app-platform"
spec:
  fromNamespace: tanzu-system-ingress

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: sreeram.sunkara@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: fluted-lambda-274409
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json